# Generated by Django 5.1.2 on 2024-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoLead',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True))
            ]
        )
    ]
