# Generated by Django 5.1.2 on 2024-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClaim',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('claim_id', models.CharField(max_length=255)),
                ('claim_status', models.CharField(max_length=255)),
                ('claimant_name', models.CharField(max_length=255)),
                ('claim_amount', models.CharField(max_length=255)),
                ('claim_date', models.CharField(max_length=255)),
                ('claim_closure_date', models.CharField(max_length=255)),
                ('claim_documents', models.CharField(max_length=255))
            ]
        )
    ]
